scratch-org-def: config/project-scratch-def.json
assign-permset: true
permset-name: CustomerID
run-apex-tests: false
delete-scratch-org: false
show-scratch-org-url: true
execute-apex:
  - scripts/CustomerIDSetup.cls